spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.206.40:3306/platform
    username: root
    password: gamec10udstud105
  jpa:
    database: MYSQL
    show-sql: true
    enerate-ddl: true
    hibernate:
      ddl-auto: update
      naming_strategy: org.hibernate.cfg.ImprovedNamingStrategy