spring:
  profiles:
    active: development
  mail:
    host: smtp.163.com
    port: 25
    username: zrb0307@163.com
    password: 15155416202
    default-encoding: UTF-8
    
  redis:
    database: 0
    host: 127.0.0.1
    password: #
    port: 6379
    pool:
      max-idle: 8
      min-idle: 0
      max-active: 8
      max-wait: -1
  freemarker:
    request-context-attribute: request
logging:
  level:
    org.springframework.web: ERROR
    org.hibernate: ERROR
server:
  context-path: /platform 
  
security:
  basic:
    enabled: false
  user:
    name: admin
    password: admin